# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
-   repo: local
    hooks:
    -   id: style_entrypoint
        name: Style Checker
        verbose: true
        require_serial: true
        language: python
        entry: python style.py